---
layout: cv
title: Daniel Wahlquist Resume
---
# Daniel Wahlquist
software enigineer, Indie Game Developer, Student at Brigham Young University of Idaho

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


## Currently

Studying Software Engineering and Game development at Brigham Young University of Idaho. Working on an indie game project called "Arcane Chronicles", which is a spellcrafting storybased RPG with over 50 quadrillion spells for players to craft in the game.

### Specialized in

python, C#, Godot, and GDscript, HTML, CSS, and javascript


### Research interests

software development, web design , and game development and design, and immersive storytelling through media. (books, games, movies, etc.)


## Education

`2023-2027`
obtaining a bachelor's degree in software engineering



## Awards

`2026`
__Most Creative Game Concept and Design__, Brigham Young University of Idaho Game Expo



### Patents




## Occupation

Cashier at Walmart, and freelance indie game developer



<!-- ### Footer

Last updated: May 2013 -->